try {
	throw Exception(1);
} catch(Exception e) {
}
